spring.application.name=openai
spring.ai.openai.api-key=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
